# Generated by Django 5.0.1 on 2024-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_accordion_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accordion",
            name="title_name",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="profile_picture",
            field=models.ImageField(
                default="testimonials/user-dummy_nn5Ltlb.png", upload_to="testimonials/"
            ),
        ),
    ]
