# Generated by Django 5.0.1 on 2024-01-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_accordion_title_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accordion",
            name="title_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="text_name",
            field=models.CharField(max_length=500),
        ),
    ]
