# Generated by Django 5.0.1 on 2024-01-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_accordion_title_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("position", models.CharField(max_length=100, null=True)),
                ("short_description", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
