# Generated by Django 5.0.1 on 2024-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_teacher_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_name", models.CharField(max_length=100)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="admin",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
