# Generated by Django 5.0.1 on 2024-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="blogs/"),
            preserve_default=False,
        ),
    ]
